version: '3'
services:
  db:
    image: postgres:latest
    container_name: dnd_postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      retries: 5

  frontend:
    image: ghcr.io/patschwendeman/react-app:latest
    platform: linux/arm64
    ports:
      - "5173:5173"

  backend:
    image: ghcr.io/patschwendeman/python-app:5ca4058f6f93c7dee2e6529b987d0c57976824ea
    platform: linux/arm64
    environment:
      - DRIVERNAME=${DRIVERNAME}
      - HOST=${HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - PORT=${PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"

volumes:
  postgres_data:
