version: '3'
services:
  dnd-frontend:
    image: ghcr.io/patschwendeman/react-app:latest
    platform: linux/arm64
    ports:
      - "5173:5173"
  dnd-backend:
    image: ghcr.io/patschwendeman/python-app:latest
    platform: linux/arm64
    ports:
      - "8000:8000"
